"""add_mikrotik_profile_to_clients

Revision ID: 090df386ee59
Revises: e83618dc84bd
Create Date: 2026-03-06 02:35:56.868882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090df386ee59'
down_revision = 'e83618dc84bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mikrotik_profile', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('mikrotik_profile')

    # ### end Alembic commands ###
