"""Add password_hash and last_login to Client model

Revision ID: e83618dc84bd
Revises: 422177b12df4
Create Date: 2026-03-05 22:19:20.608003

"""
from alembic import op
import sqlalchemy as sa
import bcrypt


# revision identifiers, used by Alembic.
revision = 'e83618dc84bd'
down_revision = '422177b12df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add columns as nullable first
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # Step 2: Generate default passwords for existing clients
    # Use PPPoE username as the default password
    connection = op.get_bind()
    clients = connection.execute(sa.text("SELECT id, pppoe_username FROM clients WHERE password_hash IS NULL")).fetchall()
    
    for client in clients:
        client_id, pppoe_username = client
        # Hash the PPPoE username as the default password
        password_bytes = pppoe_username.encode('utf-8')
        salt = bcrypt.gensalt()
        password_hash = bcrypt.hashpw(password_bytes, salt).decode('utf-8')
        
        # Update the client with the hashed password
        connection.execute(
            sa.text("UPDATE clients SET password_hash = :password_hash WHERE id = :id"),
            {"password_hash": password_hash, "id": client_id}
        )
    
    # Step 3: Make password_hash non-nullable
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('password_hash', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
